# Site settings
title: Programing go
email: 
description: > # this means to ignore newlines until "baseurl:"
  Перевод книги по программирование на go
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
